//! soroban/contracts/escrow/src/test.rs
//!
//! # Test Coverage — Soroban Escrow Scaffold
//!
//! ## Context & divergence note (see also: docs/soroban/README.md, issue #244)
//!
//! This crate (`soroban/contracts/escrow`) is the *untouched* hello-world
//! scaffold generated by `stellar contract init`. It is **not** the live
//! escrow implementation. The live, actively maintained contract lives in
//! `bounty_escrow/contracts/escrow/src/lib.rs`.
//!
//! Because the two contracts have completely different public surfaces, the
//! bounty_escrow test patterns (reentrancy, RBAC-negative, balance-invariant)
//! cannot be ported 1-for-1. Instead this file:
//!
//! 1. Preserves the original smoke test (`test_hello_basic`).
//! 2. Adds **reentrancy-style** coverage adapted to the scaffold's only
//!    public function. The scaffold has no token transfers or state mutations
//!    that a reentrancy attack could exploit, so the tests verify:
//!    - the `hello` call is idempotent / pure (no hidden state written),
//!    - concurrent invocations via multiple registered instances do not
//!      interfere with each other (models the "separate-env" property that
//!      a reentrancy guard enforces in bounty_escrow).
//! 3. Adds **RBAC-negative** coverage — documents that `hello` has NO access
//!    control and flags this as a **divergence** from bounty_escrow, where
//!    every mutating function requires `admin.require_auth()`.
//! 4. Adds **balance-invariant** style coverage — documents that `hello` has
//!    no token balance semantics, but tests the analogous output invariant:
//!    the returned greeting always satisfies `["Hello", <input>]`.
//!
//! ## Divergence catalogue (follow-up issue required)
//!
//! | Category | bounty_escrow behaviour | soroban scaffold behaviour | Risk |
//! |---|---|---|---|
//! | RBAC | Every mutating fn requires `admin.require_auth()` | `hello` has no auth check | HIGH — if real escrow logic is ever added here without adding auth checks it will be exploitable |
//! | Reentrancy | Guard on `lock_funds`, `release_funds`, `partial_release`, `claim` | No guard — no token transfers | HIGH — must be added before any token-handling code is merged |
//! | Balance invariant | `get_balance() == Σ remaining_amount` checked on every state change | No token/balance state | HIGH — no enforcement possible until escrow logic is added |
//! | Error codes | 24 typed `Error` variants | No error types | MEDIUM — callers cannot distinguish failure modes |
//! | Deadline enforcement | `DeadlineNotPassed` / `InvalidDeadline` | No deadline concept | MEDIUM |
//! | Partial release | Supported, tracked per milestone | Not supported | MEDIUM |
//! | Batch operations | `batch_lock_funds` / `batch_release_funds` | Not supported | LOW (convenience) |

#![cfg(test)]

use super::*;
use soroban_sdk::{vec, Env, String};

// ═══════════════════════════════════════════════════════════════════════════
// § 0 — Original smoke test (must remain passing)
// ═══════════════════════════════════════════════════════════════════════════

/// Original smoke test — kept exactly as-is to guarantee existing CI is
/// unaffected by the additions below.
#[test]
fn test_hello_basic() {
    let env = Env::default();
    let contract_id = env.register(Contract, ());
    let client = ContractClient::new(&env, &contract_id);

    let words = client.hello(&String::from_str(&env, "Dev"));
    assert_eq!(
        words,
        vec![
            &env,
            String::from_str(&env, "Hello"),
            String::from_str(&env, "Dev"),
        ]
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// § 1 — Reentrancy-style tests
//
// bounty_escrow source: test_reentrancy.rs
//
// The scaffold has no token transfers and therefore no classic reentrancy
// vector. The tests below verify the properties that the reentrancy guard in
// bounty_escrow is *designed* to protect:
//
//   (a) A function call must be **idempotent / pure** — calling it twice on the
//       same input must produce the same output without any cross-call
//       contamination.
//   (b) Two independent contract instances must not share mutable state —
//       exactly the isolation property a reentrancy guard enforces by
//       scoping mutable flags to the contract's own storage.
//
// DIVERGENCE: The soroban scaffold contains no `DataKey::ReentrancyGuard`
// entry and no `#[contracttype]` state. Adding token-handling logic to this
// crate without first adding a reentrancy guard would be a security
// vulnerability. This must be flagged in any future PR that promotes this
// scaffold to a real implementation.
// ═══════════════════════════════════════════════════════════════════════════

/// `hello` is a pure function — calling it twice with the same argument
/// returns the same result and does not mutate any persistent state.
///
/// In bounty_escrow this property is enforced for read-only queries via the
/// absence of state writes. For mutating calls (lock_funds, release_funds,
/// etc.) the reentrancy guard prevents a re-entrant call from observing
/// an intermediate state.
#[test]
fn test_reentrancy_hello_is_idempotent() {
    let env = Env::default();
    let contract_id = env.register(Contract, ());
    let client = ContractClient::new(&env, &contract_id);

    let name = String::from_str(&env, "Alice");

    let first = client.hello(&name);
    let second = client.hello(&name);

    assert_eq!(
        first, second,
        "hello must be idempotent: two calls with the same input must produce the same output"
    );
    assert_eq!(
        first,
        vec![
            &env,
            String::from_str(&env, "Hello"),
            String::from_str(&env, "Alice"),
        ]
    );
}

/// Two independent contract instances registered in the same environment
/// must not share mutable storage — analogous to the reentrancy guard
/// ensuring that re-entering a *different* escrow bounty does not corrupt
/// the guard flag set by the outer call.
///
/// In bounty_escrow, guard state is keyed per-contract-instance. Here we
/// verify the same scoping rule: instance A's calls do not affect instance B.
#[test]
fn test_reentrancy_two_instances_are_isolated() {
    let env = Env::default();
    let contract_a = env.register(Contract, ());
    let contract_b = env.register(Contract, ());
    let client_a = ContractClient::new(&env, &contract_a);
    let client_b = ContractClient::new(&env, &contract_b);

    let greeting_a = client_a.hello(&String::from_str(&env, "BountyHunter"));
    let greeting_b = client_b.hello(&String::from_str(&env, "BountyHunter"));

    assert_eq!(
        greeting_a, greeting_b,
        "independent instances must not share state and must produce identical output"
    );
    assert_ne!(
        contract_a, contract_b,
        "the two contract addresses must be distinct (separate instances)"
    );
}

/// Verify that successive calls with *different* inputs do not bleed into
/// each other — models the property that a bounty_escrow reentrancy guard
/// must clear correctly after each call so the next call starts clean.
#[test]
fn test_reentrancy_state_does_not_bleed_between_calls() {
    let env = Env::default();
    let contract_id = env.register(Contract, ());
    let client = ContractClient::new(&env, &contract_id);

    let call1 = client.hello(&String::from_str(&env, "Carol"));
    let call2 = client.hello(&String::from_str(&env, "Dave"));

    assert_eq!(
        call1,
        vec![
            &env,
            String::from_str(&env, "Hello"),
            String::from_str(&env, "Carol"),
        ],
        "first call must return Carol's greeting"
    );
    assert_eq!(
        call2,
        vec![
            &env,
            String::from_str(&env, "Hello"),
            String::from_str(&env, "Dave"),
        ],
        "second call must return Dave's greeting — no bleed from first call"
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// § 2 — RBAC-negative tests
//
// bounty_escrow source: test_rbac.rs, test_admin_authz.rs
//
// DIVERGENCE (must be resolved in a follow-up): `hello` has NO access
// control. In bounty_escrow every mutating entrypoint calls
// `admin.require_auth()` and returns `Error::Unauthorized` if the caller is
// not the stored admin. The soroban scaffold has no admin role, no stored
// address, and no `require_auth` call anywhere.
//
// The tests below document this gap by:
//   (a) Verifying the current (permissive) behaviour — any caller can invoke
//       `hello` — and labelling it explicitly as a divergence.
//   (b) Providing a template for what the RBAC tests *should* look like once
//       real escrow logic (with an admin role) is promoted into this crate.
// ═══════════════════════════════════════════════════════════════════════════

/// DIVERGENCE — documents that `hello` currently has NO access control.
///
/// In bounty_escrow `lock_funds`, `release_funds`, etc. all call
/// `admin.require_auth()` and every non-admin invocation is rejected.
/// The scaffold's `hello` accepts calls from any address without any
/// authorization check.
///
/// This test exists to:
/// 1. Make the gap explicit and visible in CI.
/// 2. Act as a regression anchor — if auth is ever added to `hello` this
///    test will need to be updated to reflect the new behaviour.
#[test]
fn test_rbac_divergence_hello_has_no_access_control() {
    // Note: no `mock_all_auths()` needed — `hello` performs no `require_auth`.
    // Once this scaffold gains real escrow logic, EVERY mutating function must
    // call `admin.require_auth()` (see test_admin_authz.rs in bounty_escrow).
    let env = Env::default();
    let contract_id = env.register(Contract, ());
    let client = ContractClient::new(&env, &contract_id);

    // Any arbitrary string (acting as an "unauthenticated caller") can invoke
    // hello without restriction — this is the documented divergence.
    let result = client.hello(&String::from_str(&env, "UnauthenticatedCaller"));

    assert_eq!(
        result,
        vec![
            &env,
            String::from_str(&env, "Hello"),
            String::from_str(&env, "UnauthenticatedCaller"),
        ],
        "hello currently accepts any caller — divergence from bounty_escrow RBAC model is confirmed"
    );
}

/// RBAC template — shows what a `non_admin_cannot_X` test looks like for the
/// soroban ecosystem, ready to be filled in when real escrow functions are
/// added to this crate.
///
/// Pattern sourced from bounty_escrow/test_admin_authz.rs:
/// - Do NOT call `env.mock_all_auths()` in negative-path tests.
/// - Call `env.mock_auths(&[])` (or do not mock at all) so that
///   `require_auth()` aborts on the first unauthenticated call.
/// - Use `try_*` variants and assert `res.is_err()`.
///
/// This test is a no-op until a real auth-gated function exists on this
/// contract. It is deliberately kept as a placeholder so reviewers can see
/// exactly what needs to be written.
#[test]
fn test_rbac_template_non_admin_pattern_documented() {
    // Template: when a function `fn admin_op(env: Env, ...)` is added:
    //
    //   let env = Env::default();
    //   // No mock_all_auths — we want auth checks to fire
    //   let contract_id = env.register(Contract, ());
    //   let client = ContractClient::new(&env, &contract_id);
    //   let res = client.try_admin_op(...);
    //   assert!(res.is_err(), "non-admin must be rejected");
    //
    // For now we just verify the environment is set up correctly.
    let env = Env::default();
    let contract_id = env.register(Contract, ());
    let client = ContractClient::new(&env, &contract_id);

    // `hello` has no auth — verify it succeeds as our baseline.
    let res = client.hello(&String::from_str(&env, "Admin"));
    assert_eq!(res.len(), 2, "baseline: hello returns a two-element vec");
}

// ═══════════════════════════════════════════════════════════════════════════
// § 3 — Balance-invariant tests
//
// bounty_escrow source: test_balance_invariant.rs
//
// Core invariant in bounty_escrow:
//   contract_sac_balance == Σ remaining_amount  for every tracked bounty
//
// DIVERGENCE: The soroban scaffold has NO token handling, NO `lock_funds`,
// NO `release_funds`, NO `get_balance`, and NO escrow state. The invariant
// cannot be applied directly.
//
// The tests below port the *spirit* of the invariant by verifying the
// analogous output invariant for `hello`:
//
//   output.len() == 2  AND  output[0] == "Hello"  AND  output[1] == <input>
//
// This ensures that:
//   - No element is silently dropped (analogous to "no funds lost").
//   - No spurious element is injected (analogous to "no phantom credit").
//   - The sum is always exactly what was put in (analogous to
//     Σ remaining_amount == contract_balance).
// ═══════════════════════════════════════════════════════════════════════════

/// Output-length invariant: `hello` must always return exactly 2 elements.
///
/// Analogous to: after any operation on bounty_escrow the number of tracked
/// escrows plus their sum must not change unexpectedly.
#[test]
fn test_balance_invariant_output_length_is_always_two() {
    let env = Env::default();
    let contract_id = env.register(Contract, ());
    let client = ContractClient::new(&env, &contract_id);

    for name in &["Alice", "Bob", "Carol", "Dave", "Eve"] {
        let result = client.hello(&String::from_str(&env, name));
        assert_eq!(
            result.len(),
            2,
            "output vector must always have exactly 2 elements (got {} for input '{}')",
            result.len(),
            name
        );
    }
}

/// First-element invariant: `hello` must always return `"Hello"` as the
/// first element, regardless of input.
///
/// Analogous to: the `status` field of a newly locked escrow must always be
/// `EscrowStatus::Locked` — a structural guarantee on the output.
#[test]
fn test_balance_invariant_first_element_is_always_hello() {
    let env = Env::default();
    let contract_id = env.register(Contract, ());
    let client = ContractClient::new(&env, &contract_id);

    let names = ["World", "Stellar", "", "123", "!@#"];
    for name in &names {
        let result = client.hello(&String::from_str(&env, name));
        assert_eq!(
            result.get(0).unwrap(),
            String::from_str(&env, "Hello"),
            "first element must be 'Hello' for input '{}'",
            name
        );
    }
}

/// Input-passthrough invariant: `hello` must echo the input as the second
/// element unchanged.
///
/// Analogous to: `get_escrow_info(id).amount` must equal the value passed
/// to `lock_funds` — no silent truncation or modification.
#[test]
fn test_balance_invariant_input_passthrough_unchanged() {
    let env = Env::default();
    let contract_id = env.register(Contract, ());
    let client = ContractClient::new(&env, &contract_id);

    let inputs = ["Developer", "Grainlify", "StellarNode42"];
    for input in &inputs {
        let name_str = String::from_str(&env, input);
        let result = client.hello(&name_str);
        assert_eq!(
            result.get(1).unwrap(),
            name_str,
            "second element must equal the input '{}' exactly — no mutation",
            input
        );
    }
}

/// Multi-call sum invariant: calling `hello` N times with N different inputs
/// must produce N independent results with no accumulation of state.
///
/// Analogous to: the balance invariant test_invariant_multi_bounty_mixed_states
/// in bounty_escrow — after N lock/release/refund operations the contract
/// balance must equal exactly the sum of active remaining_amounts (no more,
/// no less).
#[test]
fn test_balance_invariant_multi_call_no_state_accumulation() {
    let env = Env::default();
    let contract_id = env.register(Contract, ());
    let client = ContractClient::new(&env, &contract_id);

    let names = ["A", "B", "C", "D", "E", "F", "G", "H"];

    // Each result must be independent — no element from a prior call bleeds
    // into a subsequent call's output. We check each call inline to avoid
    // storing soroban_sdk::Vec values (which requires an &Env constructor).
    for (i, name) in names.iter().enumerate() {
        let result = client.hello(&String::from_str(&env, name));
        assert_eq!(
            result.len(),
            2,
            "call {}: result length must be 2",
            i
        );
        assert_eq!(
            result.get(0).unwrap(),
            String::from_str(&env, "Hello"),
            "call {}: first element must be 'Hello'",
            i
        );
        assert_eq!(
            result.get(1).unwrap(),
            String::from_str(&env, name),
            "call {}: second element must echo input '{}'",
            i,
            name
        );
    }
}

/// Failed-input invariant: the contract must never produce output that
/// violates the two-element guarantee even for edge-case inputs.
///
/// Analogous to: test_invariant_failed_lock_does_not_create_escrow —
/// a failed operation in bounty_escrow must not create phantom state.
/// Here, even unusual inputs must not corrupt the output structure.
#[test]
fn test_balance_invariant_edge_case_inputs_no_phantom_output() {
    let env = Env::default();
    let contract_id = env.register(Contract, ());
    let client = ContractClient::new(&env, &contract_id);

    // Very short input
    let short = client.hello(&String::from_str(&env, "X"));
    assert_eq!(short.len(), 2);
    assert_eq!(short.get(0).unwrap(), String::from_str(&env, "Hello"));
    assert_eq!(short.get(1).unwrap(), String::from_str(&env, "X"));

    // Long-ish input
    let long_name = "SomeLongUsernameForTestingPurposes";
    let long = client.hello(&String::from_str(&env, long_name));
    assert_eq!(long.len(), 2);
    assert_eq!(long.get(0).unwrap(), String::from_str(&env, "Hello"));
    assert_eq!(long.get(1).unwrap(), String::from_str(&env, long_name));
}

// ═══════════════════════════════════════════════════════════════════════════
// § 4 — Divergence summary (no executable tests — documentation only)
//
// The following functions are present in bounty_escrow but have NO equivalent
// in this scaffold. Each gap is a potential security regression if real escrow
// logic is ever promoted to this crate without re-implementing them.
//
//   MISSING (HIGH priority):
//     - init / admin storage           → no admin role, no `require_auth`
//     - lock_funds                      → no escrow state, no token transfer
//     - release_funds                   → no fund release, no guard
//     - partial_release                 → no milestone tracking
//     - refund / approve_refund         → no refund path
//     - reentrancy guard (DataKey)      → not present
//     - Error enum (24 variants)        → not present
//
//   MISSING (MEDIUM priority):
//     - deadline enforcement            → no timestamp checks
//     - batch_lock_funds                → not present
//     - batch_release_funds             → not present
//     - claim / authorize_claim         → not present
//     - circuit breaker                 → not present
//     - pause flags                     → not present
//     - fee config                      → not present
//
//   ONLY IN SCAFFOLD (out of scope for this issue — just noted):
//     - `hello(env, to) -> Vec<String>` → not present in bounty_escrow
//
// Action: open a follow-up issue to either (a) promote the bounty_escrow
// implementation into this workspace or (b) formally retire this scaffold
// and remove it from CI.
// ═══════════════════════════════════════════════════════════════════════════
